<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class MgoColumnsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('mgo_columns')->truncate();
        $mgoColumns = [
            //
            ['mgo_table_name' => 'mgo_enums', 'id' => 100, 'name' => 'id', 'display_name' => '序号', 'type' => 'bigint', 'length' => 20, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => 'ID', 'auto_increment' => 1, 'unsigned' => 1, 'data_type' => 'number', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_enums', 'id' => 101, 'name' => 'name', 'display_name' => '枚举名称', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '枚举名称', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'text', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_enums', 'id' => 102, 'name' => 'display_name', 'display_name' => '显示名称', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '显示名称', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'text', 'mgo_enum_name' => null, 'display_key' => 1, 'order_by' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_enums', 'id' => 103, 'name' => 'created_at', 'display_name' => '创建时间', 'type' => 'timestamp', 'length' => null, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '创建时间', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'datetime', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_enums', 'id' => 104, 'name' => 'updated_at', 'display_name' => '更新时间', 'type' => 'timestamp', 'length' => null, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '更新时间', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'datetime', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            //
            ['mgo_table_name' => 'mgo_enum_values', 'id' => 200, 'name' => 'id', 'display_name' => '序号', 'type' => 'bigint', 'length' => 20, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => 'ID', 'auto_increment' => 1, 'unsigned' => 1, 'data_type' => 'number', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_enum_values', 'id' => 201, 'name' => 'mgo_enum_name', 'display_name' => '关联定义枚举', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '关联定义枚举(枚举名称)', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'belongs_to', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_enum_values', 'id' => 202, 'name' => 'name', 'display_name' => '枚举值名称', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '枚举值名称', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'text', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_enum_values', 'id' => 203, 'name' => 'display_name', 'display_name' => '显示名称', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '显示名称', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'text', 'mgo_enum_name' => null, 'display_key' => 1, 'order_by' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_enum_values', 'id' => 204, 'name' => 'created_at', 'display_name' => '创建时间', 'type' => 'timestamp', 'length' => null, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '创建时间', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'datetime', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_enum_values', 'id' => 205, 'name' => 'updated_at', 'display_name' => '更新时间', 'type' => 'timestamp', 'length' => null, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '更新时间', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'datetime', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            //
            ['mgo_table_name' => 'mgo_tables', 'id' => 300, 'name' => 'id', 'display_name' => '序号', 'type' => 'bigint', 'length' => 20, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => 'ID', 'auto_increment' => 1, 'unsigned' => 1, 'data_type' => 'number', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_tables', 'id' => 301, 'name' => 'name', 'display_name' => '表名', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '表名', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'text', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_tables', 'id' => 302, 'name' => 'display_name', 'display_name' => '显示名称', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '显示名称', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'text', 'mgo_enum_name' => null, 'display_key' => 1, 'order_by' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_tables', 'id' => 303, 'name' => 'model_class', 'display_name' => '模型类名', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '模型类名', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'text', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_tables', 'id' => 304, 'name' => 'comment', 'display_name' => '备注', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '备注', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'text', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_tables', 'id' => 305, 'name' => 'migrate', 'display_name' => '迁移文件', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '迁移文件', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'text', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_tables', 'id' => 306, 'name' => 'created_at', 'display_name' => '创建时间', 'type' => 'timestamp', 'length' => null, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '创建时间', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'datetime', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 7, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_tables', 'id' => 307, 'name' => 'updated_at', 'display_name' => '更新时间', 'type' => 'timestamp', 'length' => null, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '更新时间', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'datetime', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 8, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            //
            ['mgo_table_name' => 'mgo_columns', 'id' => 400, 'name' => 'id', 'display_name' => '序号', 'type' => 'bigint', 'length' => 20, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => 'ID', 'auto_increment' => 1, 'unsigned' => 1, 'data_type' => 'number', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 9, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_columns', 'id' => 401, 'name' => 'mgo_table_name', 'display_name' => '关联定义表属性', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '关联定义表属性(表名)', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'belongs_to', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 10, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_columns', 'id' => 402, 'name' => 'name', 'display_name' => '列名称', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '列名称', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'text', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 11, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_columns', 'id' => 403, 'name' => 'display_name', 'display_name' => '显示名称', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '显示名称', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'text', 'mgo_enum_name' => null, 'display_key' => 1, 'order_by' => 12, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_columns', 'id' => 404, 'name' => 'type', 'display_name' => '列类型', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '列类型', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'enum', 'mgo_enum_name' => 'mgo_column_type', 'display_key' => 0, 'order_by' => 13, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_columns', 'id' => 405, 'name' => 'length', 'display_name' => '列长度', 'type' => 'int', 'length' => 11, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '列长度', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'text', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 14, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_columns', 'id' => 406, 'name' => 'decimals', 'display_name' => '小数点长度', 'type' => 'int', 'length' => 11, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '小数点长度', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'text', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 15, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_columns', 'id' => 407, 'name' => 'not_null', 'display_name' => '是否不为空', 'type' => 'boolean', 'length' => 1, 'decimals' => null, 'not_null' => 1, 'default' => '0', 'comment' => '是否不为空', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'boolean', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 16, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_columns', 'id' => 408, 'name' => 'default', 'display_name' => '默认值', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '默认值', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'text', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 17, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_columns', 'id' => 409, 'name' => 'comment', 'display_name' => '备注', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '备注', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'text', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 18, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_columns', 'id' => 410, 'name' => 'auto_increment', 'display_name' => '是否自增', 'type' => 'boolean', 'length' => 1, 'decimals' => null, 'not_null' => 1, 'default' => '0', 'comment' => '是否自增', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'boolean', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 19, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_columns', 'id' => 411, 'name' => 'unsigned', 'display_name' => '是否无符号', 'type' => 'boolean', 'length' => 1, 'decimals' => null, 'not_null' => 1, 'default' => '0', 'comment' => '是否无符号', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'boolean', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 20, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_columns', 'id' => 412, 'name' => 'data_type', 'display_name' => '数据类型', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => 'text', 'comment' => '数据类型', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'enum', 'mgo_enum_name' => 'mgo_column_data_type', 'display_key' => 0, 'order_by' => 21, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_columns', 'id' => 413, 'name' => 'mgo_enum_name', 'display_name' => '关联定义枚举', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '关联定义枚举(枚举名称)', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'belongs_to', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 22, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_columns', 'id' => 414, 'name' => 'display_key', 'display_name' => '是否展示键', 'type' => 'boolean', 'length' => 1, 'decimals' => null, 'not_null' => 1, 'default' => '0', 'comment' => '是否展示键', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'boolean', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 23, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_columns', 'id' => 415, 'name' => 'order_by', 'display_name' => '排序', 'type' => 'bigint', 'length' => 20, 'decimals' => null, 'not_null' => 1, 'default' => '0', 'comment' => '排序', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'number', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 24, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_columns', 'id' => 416, 'name' => 'created_at', 'display_name' => '创建时间', 'type' => 'timestamp', 'length' => null, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '创建时间', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'datetime', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 25, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_columns', 'id' => 417, 'name' => 'updated_at', 'display_name' => '更新时间', 'type' => 'timestamp', 'length' => null, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '更新时间', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'datetime', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 26, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            //
            ['mgo_table_name' => 'mgo_indices', 'id' => 500, 'name' => 'id', 'display_name' => '序号', 'type' => 'bigint', 'length' => 20, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => 'ID', 'auto_increment' => 1, 'unsigned' => 1, 'data_type' => 'number', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_indices', 'id' => 501, 'name' => 'mgo_table_name', 'display_name' => '关联定义表属性', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '关联定义表属性(表名)', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'belongs_to', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_indices', 'id' => 502, 'name' => 'name', 'display_name' => '索引名称', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '索引名称', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'text', 'mgo_enum_name' => null, 'display_key' => 1, 'order_by' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_indices', 'id' => 503, 'name' => 'fields', 'display_name' => '索引字段', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '索引字段(["name"])', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'text', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_indices', 'id' => 504, 'name' => 'type', 'display_name' => '索引类型', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '索引类型(PRIMARY, UNIQUE)', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'enum', 'mgo_enum_name' => "mgo_index_type", 'display_key' => 0, 'order_by' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_indices', 'id' => 505, 'name' => 'method', 'display_name' => '索引算法', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '索引算法(BTREE, HASH)', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'enum', 'mgo_enum_name' => "mgo_index_method", 'display_key' => 0, 'order_by' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_indices', 'id' => 506, 'name' => 'comment', 'display_name' => '备注', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => 'BTREE', 'comment' => '备注', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'text', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 7, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_indices', 'id' => 507, 'name' => 'created_at', 'display_name' => '创建时间', 'type' => 'timestamp', 'length' => null, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '创建时间', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'datetime', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 25, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_indices', 'id' => 508, 'name' => 'updated_at', 'display_name' => '更新时间', 'type' => 'timestamp', 'length' => null, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '更新时间', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'datetime', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 26, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            //
            ['mgo_table_name' => 'mgo_foreigns', 'id' => 600, 'name' => 'id', 'display_name' => '序号', 'type' => 'bigint', 'length' => 20, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => 'ID', 'auto_increment' => 1, 'unsigned' => 1, 'data_type' => 'number', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_foreigns', 'id' => 601, 'name' => 'mgo_table_name', 'display_name' => '关联定义表属性', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '关联定义表属性(表名)', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'belongs_to', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_foreigns', 'id' => 602, 'name' => 'name', 'display_name' => '外键名称', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '外键名称', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'text', 'mgo_enum_name' => null, 'display_key' => 1, 'order_by' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_foreigns', 'id' => 603, 'name' => 'mgo_column_id', 'display_name' => '外键字段ID', 'type' => 'bigint', 'length' => 20, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '外键字段ID(关联定义列属性)(列ID)', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'belongs_to', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_foreigns', 'id' => 604, 'name' => 'referenced_mgo_table_name', 'display_name' => '外键关联表', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '外键关联表(关联定义表属性)(表名)', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'belongs_to', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_foreigns', 'id' => 605, 'name' => 'referenced_mgo_column_id', 'display_name' => '外键关联字段ID', 'type' => 'bigint', 'length' => 20, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '外键关联字段ID(关联定义列属性)(列ID)', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'belongs_to', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_foreigns', 'id' => 606, 'name' => 'on_update', 'display_name' => '更新约束', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => 'CASCADE', 'comment' => '更新约束(CASCADE,SET NULL,RESTRICT,NO ACTION)', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'enum', 'mgo_enum_name' => 'mgo_foreigns_on_update', 'display_key' => 0, 'order_by' => 7, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_foreigns', 'id' => 607, 'name' => 'on_delete', 'display_name' => '删除约束', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => 'RESTRICT', 'comment' => '删除约束(CASCADE,SET NULL,RESTRICT,NO ACTION)', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'enum', 'mgo_enum_name' => 'mgo_foreigns_on_delete', 'display_key' => 0, 'order_by' => 8, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_foreigns', 'id' => 608, 'name' => 'created_at', 'display_name' => '创建时间', 'type' => 'timestamp', 'length' => null, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '创建时间', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'datetime', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 9, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_foreigns', 'id' => 609, 'name' => 'updated_at', 'display_name' => '更新时间', 'type' => 'timestamp', 'length' => null, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '更新时间', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'datetime', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 10, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            //
            ['mgo_table_name' => 'mgo_guards', 'id' => 700, 'name' => 'id', 'display_name' => '序号', 'type' => 'bigint', 'length' => 20, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => 'ID', 'auto_increment' => 1, 'unsigned' => 1, 'data_type' => 'number', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_guards', 'id' => 701, 'name' => 'name', 'display_name' => '守卫名称', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '守卫名称', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'text', 'mgo_enum_name' => null, 'display_key' => 1, 'order_by' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_guards', 'id' => 702, 'name' => 'created_at', 'display_name' => '创建时间', 'type' => 'timestamp', 'length' => null, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '创建时间', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'datetime', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_guards', 'id' => 703, 'name' => 'updated_at', 'display_name' => '更新时间', 'type' => 'timestamp', 'length' => null, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '更新时间', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'datetime', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            //
            ['mgo_table_name' => 'mgo_pages', 'id' => 800, 'name' => 'id', 'display_name' => '序号', 'type' => 'bigint', 'length' => 20, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => 'ID', 'auto_increment' => 1, 'unsigned' => 1, 'data_type' => 'number', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_pages', 'id' => 801, 'name' => 'mgo_guard_id', 'display_name' => '关联定义守卫', 'type' => 'bigint', 'length' => 20, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '关联定义守卫(守卫ID)', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'belongs_to', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_pages', 'id' => 802, 'name' => 'name', 'display_name' => '页面名称', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '页面名称', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'text', 'mgo_enum_name' => null, 'display_key' => 1, 'order_by' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_pages', 'id' => 803, 'name' => 'created_at', 'display_name' => '创建时间', 'type' => 'timestamp', 'length' => null, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '创建时间', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'datetime', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_pages', 'id' => 804, 'name' => 'updated_at', 'display_name' => '更新时间', 'type' => 'timestamp', 'length' => null, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '更新时间', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'datetime', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            //
            ['mgo_table_name' => 'mgo_modules', 'id' => 900, 'name' => 'id', 'display_name' => '序号', 'type' => 'bigint', 'length' => 20, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => 'ID', 'auto_increment' => 1, 'unsigned' => 1, 'data_type' => 'number', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_modules', 'id' => 901, 'name' => 'mgo_page_id', 'display_name' => '关联定义页面', 'type' => 'bigint', 'length' => 20, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '关联定义页面(页面ID)', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'belongs_to', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_modules', 'id' => 902, 'name' => 'name', 'display_name' => '模块名称', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '模块名称', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'text', 'mgo_enum_name' => null, 'display_key' => 1, 'order_by' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_modules', 'id' => 903, 'name' => 'mgo_table_name', 'display_name' => '模块主表名', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '模块主表名(关联定义表属性)(表名)', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'belongs_to', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_modules', 'id' => 904, 'name' => 'type', 'display_name' => '模块类型', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '模块类型(index,list,tree,charts,view)', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'enum', 'mgo_enum_name' => 'mgo_module_type', 'display_key' => 0, 'order_by' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_modules', 'id' => 905, 'name' => 'attr', 'display_name' => '模块属性', 'type' => 'text', 'length' => null, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '模块属性', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'text', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_modules', 'id' => 906, 'name' => 'order_by', 'display_name' => '排序', 'type' => 'bigint', 'length' => 20, 'decimals' => null, 'not_null' => 1, 'default' => '0', 'comment' => '排序', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'number', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 7, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_modules', 'id' => 907, 'name' => 'created_at', 'display_name' => '创建时间', 'type' => 'timestamp', 'length' => null, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '创建时间', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'datetime', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 8, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_modules', 'id' => 908, 'name' => 'updated_at', 'display_name' => '更新时间', 'type' => 'timestamp', 'length' => null, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '更新时间', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'datetime', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 9, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            //
            ['mgo_table_name' => 'mgo_features', 'id' => 1000, 'name' => 'id', 'display_name' => '序号', 'type' => 'bigint', 'length' => 20, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => 'ID', 'auto_increment' => 1, 'unsigned' => 1, 'data_type' => 'number', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_features', 'id' => 1001, 'name' => 'mgo_module_id', 'display_name' => '关联定义模块', 'type' => 'bigint', 'length' => 20, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '关联定义模块(模块ID)', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'belongs_to', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_features', 'id' => 1002, 'name' => 'name', 'display_name' => '功能名称', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '模块名称', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'text', 'mgo_enum_name' => null, 'display_key' => 1, 'order_by' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_features', 'id' => 1003, 'name' => 'type', 'display_name' => '功能类型', 'type' => 'varchar', 'length' => 191, 'decimals' => null, 'not_null' => 1, 'default' => '', 'comment' => '功能类型(add,delete,update,view,share,...)', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'enum', 'mgo_enum_name' => 'mgo_feature_type', 'display_key' => 0, 'order_by' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_features', 'id' => 1004, 'name' => 'attr', 'display_name' => '功能属性', 'type' => 'text', 'length' => null, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '模块属性', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'text', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_features', 'id' => 1005, 'name' => 'created_at', 'display_name' => '创建时间', 'type' => 'timestamp', 'length' => null, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '创建时间', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'datetime', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 8, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['mgo_table_name' => 'mgo_features', 'id' => 1006, 'name' => 'updated_at', 'display_name' => '更新时间', 'type' => 'timestamp', 'length' => null, 'decimals' => null, 'not_null' => 0, 'default' => '', 'comment' => '更新时间', 'auto_increment' => 0, 'unsigned' => 0, 'data_type' => 'datetime', 'mgo_enum_name' => null, 'display_key' => 0, 'order_by' => 9, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

        ];
        DB::table('mgo_columns')->insert($mgoColumns);
    }
}
